
> ingaialab@1.0.0 test /home/rodrigo/ingaialab
> jest --passWithNoTests --silent --noStackTrace --runInBand --no-cache

ts-jest[config] (WARN) There is a mismatch between your NodeJs version v10.23.0 and your TypeScript target es2019. This might lead to some unexpected errors when running tests with `ts-jest`. To fix this, you can check https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping
PASS src/tests/property.spec.ts (20.931 s)
PASS src/tests/calc-property-price.spec.ts
PASS src/tests/square-meter.spec.ts
FAIL src/tests/get-square-meter.spec.ts
  ‚óè Test suite failed to run

    [96msrc/tests/get-square-meter.spec.ts[0m:[93m1[0m:[93m10[0m - [91merror[0m[90m TS2724: [0m'"../data/protocols/get-square-meters-repository"' has no exported member named 'GetSquareMeterRepository'. Did you mean 'GetSquareMetersRepository'?

    [7m1[0m import { GetSquareMeterRepository } from '@Data/protocols/get-square-meters-repository'
    [7m [0m [91m         ~~~~~~~~~~~~~~~~~~~~~~~~[0m
    [96msrc/tests/get-square-meter.spec.ts[0m:[93m2[0m:[93m35[0m - [91merror[0m[90m TS2307: [0mCannot find module '@Data/usecases/get-square-meters/db-get-square-meters' or its corresponding type declarations.

    [7m2[0m import { DbGetSquareMeters } from '@Data/usecases/get-square-meters/db-get-square-meters'
    [7m [0m [91m                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m

FAIL src/tests/property-repository.spec.ts
  ‚óè Property [DB] Repository ‚Ä∫ Should return the cost of property on success

    connect ECONNREFUSED 127.0.0.1:5000

FAIL src/tests/square-meters-repository.spec.ts
  ‚óè Test suite failed to run

    [96msrc/infra/db/square-meters-repository/square-meters.ts[0m:[93m1[0m:[93m10[0m - [91merror[0m[90m TS2724: [0m'"../../../data/protocols/get-square-meters-repository"' has no exported member named 'GetSquareMeterRepository'. Did you mean 'GetSquareMetersRepository'?

    [7m1[0m import { GetSquareMeterRepository } from '@Data/protocols/get-square-meters-repository'
    [7m [0m [91m         ~~~~~~~~~~~~~~~~~~~~~~~~[0m

PASS src/tests/square-meter-validator.spec.ts
FAIL src/tests/body-parser.test.ts
  ‚óè Body parser Middleware ‚Ä∫ Should parse body as json




ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at Object.getCodec (node_modules/iconv-lite/lib/index.js:65:27)
      at Object.getDecoder (node_modules/iconv-lite/lib/index.js:127:23)
      at getDecoder (node_modules/raw-body/index.js:45:18)
      at readStream (node_modules/raw-body/index.js:180:15)
      at getRawBody (node_modules/raw-body/index.js:108:12)
FAIL src/tests/content-type.test.ts
  ‚óè Content Type Middleware ‚Ä∫ Should return default content type as json

    Configuration error:

    Could not locate module @Data/usecases/get-square-meters/db-get-square-meters mapped as:
    /home/rodrigo/ingaialab/src/data$1.

    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/@Data(.*)$/": "/home/rodrigo/ingaialab/src/data$1"
      },
      "resolver": undefined
    }

(node:82083) UnhandledPromiseRejectionWarning: Error: Caught error after test environment was torn down

expected { name: 'rodrigo' } response body, got {}
(node:82083) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:82083) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
FAIL src/tests/cors.test.ts
  ‚óè CORS Middleware ‚Ä∫ Should enable CORS

    Configuration error:

    Could not locate module @Data/usecases/get-square-meters/db-get-square-meters mapped as:
    /home/rodrigo/ingaialab/src/data$1.

    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/@Data(.*)$/": "/home/rodrigo/ingaialab/src/data$1"
      },
      "resolver": undefined
    }

FAIL src/tests/property-routes.test.ts
  ‚óè Property Routes ‚Ä∫ Should return a calc of property on success

    Configuration error:

    Could not locate module @Data/usecases/get-square-meters/db-get-square-meters mapped as:
    /home/rodrigo/ingaialab/src/data$1.

    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/@Data(.*)$/": "/home/rodrigo/ingaialab/src/data$1"
      },
      "resolver": undefined
    }

Test Suites: 7 failed, 4 passed, 11 total
Tests:       5 failed, 13 passed, 18 total
Snapshots:   0 total
Time:        40.336 s

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at Object.getCodec (node_modules/iconv-lite/lib/index.js:65:27)
      at Object.getDecoder (node_modules/iconv-lite/lib/index.js:127:23)
      at getDecoder (node_modules/raw-body/index.js:45:18)
      at readStream (node_modules/raw-body/index.js:180:15)
      at getRawBody (node_modules/raw-body/index.js:108:12)
(node:82083) UnhandledPromiseRejectionWarning: Error: Caught error after test environment was torn down

expected 200 "OK", got 415 "Unsupported Media Type"
(node:82083) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
(node:82083) UnhandledPromiseRejectionWarning: MongoServerSelectionError: Caught error after test environment was torn down

connect ECONNREFUSED 0.0.0.0:27017
(node:82083) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
npm ERR! Test failed.  See above for more details.

> ingaialab@1.0.0 test /home/rodrigo/ingaialab
> jest --passWithNoTests --silent --noStackTrace --runInBand --no-cache

ts-jest[config] (WARN) There is a mismatch between your NodeJs version v10.23.0 and your TypeScript target es2019. This might lead to some unexpected errors when running tests with `ts-jest`. To fix this, you can check https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping
PASS src/tests/property.spec.ts (17.167 s)
PASS src/tests/calc-property-price.spec.ts
PASS src/tests/square-meter.spec.ts
FAIL src/tests/get-square-meter.spec.ts
  ‚óè Test suite failed to run

    [96msrc/tests/get-square-meter.spec.ts[0m:[93m12[0m:[93m15[0m - [91merror[0m[90m TS2416: [0mProperty 'get' in type 'GetSquareMeterRepositoryStub' is not assignable to the same property in base type 'GetSquareMeterRepository'.
      Type '() => Promise<number>' is not assignable to type '() => number'.
        Type 'Promise<number>' is not assignable to type 'number'.

    [7m12[0m         async get (): Promise<number> {
    [7m  [0m [91m              ~~~[0m
    [96msrc/tests/get-square-meter.spec.ts[0m:[93m16[0m:[93m5[0m - [91merror[0m[90m TS2322: [0mType 'GetSquareMeterRepositoryStub' is not assignable to type 'GetSquareMeterRepository'.
      Types of property 'get' are incompatible.
        Type '() => Promise<number>' is not assignable to type '() => number'.

    [7m16[0m     return new GetSquareMeterRepositoryStub()
    [7m  [0m [91m    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m

FAIL src/tests/property-repository.spec.ts
  ‚óè Property [DB] Repository ‚Ä∫ Should return the cost of property on success

    connect ECONNREFUSED 127.0.0.1:5000

FAIL src/tests/square-meters-repository.spec.ts
  ‚óè Test suite failed to run

    [96msrc/infra/db/square-meters-repository/square-meters.ts[0m:[93m5[0m:[93m11[0m - [91merror[0m[90m TS2416: [0mProperty 'get' in type 'SquareMetersDbRepository' is not assignable to the same property in base type 'GetSquareMeterRepository'.
      Type '() => Promise<number>' is not assignable to type '() => number'.
        Type 'Promise<number>' is not assignable to type 'number'.

    [7m5[0m     async get (): Promise<number> {
    [7m [0m [91m          ~~~[0m

PASS src/tests/square-meter-validator.spec.ts
FAIL src/tests/body-parser.test.ts
  ‚óè Body parser Middleware ‚Ä∫ Should parse body as json




ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at Object.getCodec (node_modules/iconv-lite/lib/index.js:65:27)
      at Object.getDecoder (node_modules/iconv-lite/lib/index.js:127:23)
      at getDecoder (node_modules/raw-body/index.js:45:18)
      at readStream (node_modules/raw-body/index.js:180:15)
      at getRawBody (node_modules/raw-body/index.js:108:12)
(node:82340) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
(node:82340) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
(node:82340) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
FAIL src/tests/content-type.test.ts
  ‚óè Content Type Middleware ‚Ä∫ Should return default content type as json

    Caught error after test environment was torn down

    expected { name: 'rodrigo' } response body, got {}

FAIL src/tests/cors.test.ts
  ‚óè CORS Middleware ‚Ä∫ Should enable CORS

    connect ECONNREFUSED 127.0.0.1:5000


ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at Object.getCodec (node_modules/iconv-lite/lib/index.js:65:27)
      at Object.getDecoder (node_modules/iconv-lite/lib/index.js:127:23)
      at getDecoder (node_modules/raw-body/index.js:45:18)
      at readStream (node_modules/raw-body/index.js:180:15)
      at getRawBody (node_modules/raw-body/index.js:108:12)
FAIL src/tests/property-routes.test.ts
  ‚óè Property Routes ‚Ä∫ Should return a calc of property on success

    connect ECONNREFUSED 127.0.0.1:5000

Test Suites: 7 failed, 4 passed, 11 total
Tests:       5 failed, 13 passed, 18 total
Snapshots:   0 total
Time:        34.998 s
(node:82340) UnhandledPromiseRejectionWarning: Error: Caught error after test environment was torn down

expected 200 "OK", got 415 "Unsupported Media Type"
(node:82340) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
(node:82340) UnhandledPromiseRejectionWarning: MongoServerSelectionError: Caught error after test environment was torn down

connect ECONNREFUSED 0.0.0.0:27017
(node:82340) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
npm ERR! Test failed.  See above for more details.

> ingaialab@1.0.0 test /home/rodrigo/ingaialab
> jest --passWithNoTests --silent --noStackTrace --runInBand --no-cache

ts-jest[config] (WARN) There is a mismatch between your NodeJs version v10.23.0 and your TypeScript target es2019. This might lead to some unexpected errors when running tests with `ts-jest`. To fix this, you can check https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping
PASS src/tests/property.spec.ts (18.901 s)
PASS src/tests/calc-property-price.spec.ts
PASS src/tests/square-meter.spec.ts
PASS src/tests/get-square-meter.spec.ts
FAIL src/tests/property-repository.spec.ts
  ‚óè Property [DB] Repository ‚Ä∫ Should return the cost of property on success

    connect ECONNREFUSED 127.0.0.1:5000

FAIL src/tests/square-meters-repository.spec.ts (6.634 s)
  ‚óè SquareMeters [DB] Repository ‚Ä∫ Should return the cost of m¬≤ on success

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

PASS src/tests/square-meter-validator.spec.ts

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at Object.getCodec (node_modules/iconv-lite/lib/index.js:65:27)
      at Object.getDecoder (node_modules/iconv-lite/lib/index.js:127:23)
      at getDecoder (node_modules/raw-body/index.js:45:18)
      at readStream (node_modules/raw-body/index.js:180:15)
      at getRawBody (node_modules/raw-body/index.js:108:12)
FAIL src/tests/body-parser.test.ts
  ‚óè Body parser Middleware ‚Ä∫ Should parse body as json

    connect ECONNREFUSED 127.0.0.1:5000

FAIL src/tests/content-type.test.ts
  ‚óè Content Type Middleware ‚Ä∫ Should return default content type as json

    Caught error after test environment was torn down

    expected { name: 'rodrigo' } response body, got {}

FAIL src/tests/cors.test.ts
  ‚óè CORS Middleware ‚Ä∫ Should enable CORS

    connect ECONNREFUSED 127.0.0.1:5000

FAIL src/tests/property-routes.test.ts
  ‚óè Property Routes ‚Ä∫ Should return a calc of property on success

    connect ECONNREFUSED 127.0.0.1:5000

Test Suites: 6 failed, 5 passed, 11 total
Tests:       6 failed, 14 passed, 20 total
Snapshots:   0 total
Time:        43.902 s
(node:82408) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
(node:82408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:82408) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at Object.getCodec (node_modules/iconv-lite/lib/index.js:65:27)
      at Object.getDecoder (node_modules/iconv-lite/lib/index.js:127:23)
      at getDecoder (node_modules/raw-body/index.js:45:18)
      at readStream (node_modules/raw-body/index.js:180:15)
      at getRawBody (node_modules/raw-body/index.js:108:12)
(node:82408) UnhandledPromiseRejectionWarning: Error: Caught error after test environment was torn down

expected 200 "OK", got 415 "Unsupported Media Type"
(node:82408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
(node:82408) UnhandledPromiseRejectionWarning: MongoServerSelectionError: Caught error after test environment was torn down

connect ECONNREFUSED 0.0.0.0:27017
(node:82408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
(node:82408) UnhandledPromiseRejectionWarning: MongoServerSelectionError: Caught error after test environment was torn down

connect ECONNREFUSED 0.0.0.0:27017
(node:82408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
npm ERR! Test failed.  See above for more details.
